config/routes.rb
Rails.application.routes.draw do

  get 'designs/paper'

  resources :credit_cards, path: '/payments'
  devise_for :users, :path_names => {:sign_in => 'signin', :sign_up => 'register', :sign_out => 'logout'},
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static#index'

  scope module: 'admin', path: '/admin' do
    resources :users
    get 'users/:id/message',  to: 'users#send_message', as: 'test_push_message'
  end

  get 'admin',  to: 'static#admin', as: 'admin_panel'
  get 'thankyou',  to: 'static#thankyou', as: 'thankyou'

  namespace :api do
    namespace :v1, format: :json do
      devise_scope :user do
        post 'login', to: 'sessions#create'
        post 'sign_up', to: 'registrations#create'
        get 'logout', to: 'sessions#destroy'
      end
    end
  end

end

app/models/credit_card.rb
# == Schema Information
#
# Table name: credit_cards
#
#  id               :integer          not null, primary key
#  name_on_card     :string
#  card_number      :string
#  expiration_month :integer
#  expiration_year  :integer
#  cvv              :string
#  zip_code         :string
#  card_type        :string
#  stripe_id        :string
#  last_4_digits    :string
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class CreditCard < ApplicationRecord
  belongs_to :user

  validates_presence_of :name_on_card
  validates_presence_of :card_number
  validates_presence_of :exp_month
  validates_presence_of :exp_year
  validates_presence_of :cvc
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = current_user.credit_cards
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|

      if @credit_card.valid?
        #save card information in Stripe Service
        service = CreditCardService.new(current_user)
        @saved_credit_card = service.create_card(credit_card_params)

        if (@saved_credit_card.present?)

          puts '----------- Done saving card -----------------'
          puts '@saved_credit_card here!!'
          puts '-----------------------------------------------'

          format.html { redirect_to credit_cards_path, notice: 'Credit card was successfully created.' }
          format.json { render :show, status: :created, location: @saved_credit_card }
        else
          service.copy_errors(@credit_card)
          format.html { render :new }
          format.json { render json: @credit_card.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    service = CreditCardService.new(current_user)
    service.delete_card(@credit_card)

    respond_to do |format|
      if( service.errors? )
        format.html { redirect_to credit_cards_path, notice: @credit_card.errors.full_messages.first }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      else
        @credit_card.destroy
        format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_credit_card
    @credit_card = CreditCard.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def credit_card_params
    params.require(:credit_card).permit(:name_on_card, :card_number, :exp_month, :exp_year, :cvc, :zip_code, :card_type, :user_id)
  end

end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper

  def card_icon(credit_card)
    # Visa, American Express, MasterCard, Discover, JCB, Diners Club, or Unknown.
    if (credit_card.card_type == 'Visa')
      return 'fa-cc-visa'
    elsif (credit_card.card_type == 'American Express')
      return 'fa-cc-amex'
    elsif (credit_card.card_type == 'MasterCard')
      return 'fa-cc-mastercard'
    elsif (credit_card.card_type == 'Discover')
      return 'fa-cc-discover'
    else
      return 'fa-credit-card'
    end
  end

  def card_mask( credit_card )
    return 'xxxx-xxxx-xxxx-' + credit_card.last_4_digits
  end

  def expiration_date( credit_card )
    if( credit_card.exp_month < 10 )
      return '0' + credit_card.exp_month.to_s + '/' + credit_card.exp_year.to_s
    end

    return credit_card.exp_month.to_s + '/' + credit_card.exp_year.to_s
  end
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card, html: {class: "form-horizontal", role: "form"}) do |f| %>
    <% if @credit_card.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h4>

          <ul>
            <% @credit_card.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name_on_card, class: "col-sm-4 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :name_on_card, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :card_number, class: "col-sm-4 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :card_number, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :expiration_month, class: "col-sm-4 control-label" %>
      <div class="col-sm-8">
        <%= select_month @credit_card.exp_month, {add_month_numbers: true}, {name: 'credit_card[exp_month]', id: "expiration_month", class: "form-control"} %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :expiration_year, class: "col-sm-4 control-label" %>
      <div class="col-sm-8">
        <%= select_year @credit_card.exp_year, {start_year: Date.today.year, end_year: Date.today.year+7}, {name: 'credit_card[exp_year]', id: "expiration_year", class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label 'Security code', class: "col-sm-4 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :cvc, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/credit_cards/edit.html.erb
<div class="page-header">
  <%= link_to credit_cards_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @credit_card, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing credit_card</h1>
</div>

<%= render 'form' %>

app/views/credit_cards/index.html.erb
<div class="page-header">
  <%= link_to new_credit_card_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Card
  <% end %>
  <h1>Available Credit cards</h1>
</div>

<% if @credit_cards.empty? %>
    <h3>No credit cards on file.</h3>
<% else %>

    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th>Name on card</th>
          <th>Card number</th>
          <th>Expiration</th>
          <th>Card type</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <%= content_tag_for(:tr, @credit_cards) do |credit_card| %>
            <td><%= credit_card.name_on_card %></td>
            <td><%= card_mask(credit_card) %></td>
            <td><%= expiration_date(credit_card) %></td>
            <td><i class="fa fa-2x <%= card_icon(credit_card) %>"></i></td>
            <td>
              <%= link_to credit_card, method: :delete, data: {confirm: 'Are you sure want to delete this credit card?'}, class: 'btn btn-xs btn-danger' do %>
                <i class="fa fa-remove"></i>
              <% end %>
            </td>
        <% end %>
        </tbody>
      </table>
    </div>

<% end %>

app/views/credit_cards/new.html.erb
<div class="container" style="padding-top: 20px;">

  <div class="row">
    <div class="col-lg-6 col-md-6 col-md-offset-3">

      <h2 style="text-align: center"><i class="fa fa-credit-card" style="color: #007dff"></i> New Credit Card</h2>

      <div class="panel panel-default">
        <div class="panel-body" style="padding-top: 35px;">

          <%= render 'form' %>

        </div>
      </div>

    </div>

  </div>
</div>

app/views/credit_cards/show.html.erb
<div class="page-header">
  <%= link_to credit_cards_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_credit_card_path(@credit_card), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show credit_card</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name on card:</dt>
  <dd><%= @credit_card.name_on_card %></dd>

  <dt>Card number:</dt>
  <dd><%= @credit_card.card_number %></dd>

  <dt>Expiration month:</dt>
  <dd><%= @credit_card.expiration_month %></dd>

  <dt>Expiration year:</dt>
  <dd><%= @credit_card.expiration_year %></dd>

  <dt>Cvv:</dt>
  <dd><%= @credit_card.cvv %></dd>

  <dt>Zip code:</dt>
  <dd><%= @credit_card.zip_code %></dd>

  <dt>Card type:</dt>
  <dd><%= @credit_card.card_type %></dd>

  <dt>User:</dt>
  <dd><%= @credit_card.user %></dd>

</dl>