config/routes.rb
Rails.application.routes.draw do

  get 'designs/paper'

  resources :credit_cards, path: '/payments'
  devise_for :users, :path_names => {:sign_in => 'signin', :sign_up => 'register', :sign_out => 'logout'},
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static#index'

  scope module: 'admin', path: '/admin' do
    resources :users
    get 'users/:id/message',  to: 'users#send_message', as: 'test_push_message'
  end

  get 'admin',  to: 'static#admin', as: 'admin_panel'
  get 'thankyou',  to: 'static#thankyou', as: 'thankyou'

  namespace :api do
    namespace :v1, format: :json do
      devise_scope :user do
        post 'login', to: 'sessions#create'
        post 'sign_up', to: 'registrations#create'
        get 'logout', to: 'sessions#destroy'
      end
    end
  end

end

app/views/shared/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SAAS Starter</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

      <div class="navbar-form navbar-right">

        <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, :method => :delete do %>
                <button class="btn btn-success">Sign Out</button>
            <% end %>
            <%= link_to credit_cards_path do %>
                <button class="btn btn-default">Payments</button>
            <% end %>
            <% if current_user.admin? %>
                <%= link_to admin_panel_path do %>
                    <button class="btn btn-success">Admin</button>
                <% end %>
            <% end %>
        <% else %>
            <%= link_to new_user_registration_path do %>
                <button class="btn btn-success">Sign Up</button>
            <% end %>
            <%= link_to new_user_session_path do %>
                <button class="btn btn-success">Sign In</button>
            <% end %>
        <% end %>

      </div>
    </div>
    <!--/.navbar-collapse -->
  </div>
</nav>