config/routes.rb
Rails.application.routes.draw do

  get 'designs/paper'

  resources :credit_cards, path: '/payments'
  devise_for :users, :path_names => {:sign_in => 'signin', :sign_up => 'register', :sign_out => 'logout'},
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static#index'

  scope module: 'admin', path: '/admin' do
    resources :users
    get 'users/:id/message',  to: 'users#send_message', as: 'test_push_message'
  end

  get 'admin',  to: 'static#admin', as: 'admin_panel'
  get 'thankyou',  to: 'static#thankyou', as: 'thankyou'

  namespace :api do
    namespace :v1, format: :json do
      devise_scope :user do
        post 'login', to: 'sessions#create'
        post 'sign_up', to: 'registrations#create'
        get 'logout', to: 'sessions#destroy'
      end
    end
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="manifest" href="/manifest.json">

  <title>Sales Joy</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.2/js/tether.js"></script>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<%= render 'shared/menu' %>

<% flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
    <% end %>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><%= link_to "Users", users_path %></li>
      </ul>
    </div>


    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <%= yield %>
    </div>

  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SAAS Starter</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/menu' %>

<% flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
    <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/empty.html.erb
<%= yield %>

app/views/layouts/paper.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SAAS Starter</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'paper', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/menu' %>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
      <% end %>
  <% end %>

  <%= yield %>

</div>
</body>
</html>